"""
Convert hand-labeled 3D keypoints (picked on a car CAD mesh in Blender) into
a per-model Apollo-24 keypoint template in this project's (x, h, z)
convention (see build_car_template()'s docstring).

Only 12 of the 24 keypoints are hand-labeled (one representative per
left/right pair, per _LR_PAIRS); the other 12 are generated by mirroring.
A 13th point, ground_ref, is required for establishing the true h=0 ground
plane in the raw (Blender) coordinate frame — see detect_axes().

Blender's own coordinate frame (which raw axis is lateral/longitudinal/
height, and which signs) is detected from the data itself rather than
hardcoded, since it depends on importer behavior that shouldn't be assumed
without verification. See docs/keypoints-openpifpaf-wheel-pair-localizer.md
and docs/localization-methods.md for the surrounding localization context.
"""
from __future__ import annotations

from typing import Optional

import numpy as np

from trafficlab.motion.keypoints_openpifpaf import KP_NAMES, _LR_PAIRS, build_car_template

GROUND_REF_NAME = "ground_ref"

# Cross-check bands / thresholds used by detect_axes and build_template.
_LON_WHEELBASE_BAND_M = (2.0, 3.1)     # expected |rear-front| on the true longitudinal axis
_LAT_TRACK_DELTA_MAX_M = 0.2           # expected |rear-front| on the true lateral axis (should be ~0)
_LAT_DISAGREE_HARD_ABORT_M = 0.05      # a *_left point on the "wrong" side beyond this is a real error
_GROUND_FALLBACK_BAND_M = (0.15, 0.50)  # wheel-hub-above-true-ground sanity band


def expected_left_names() -> list[str]:
    """The 12 *_left keypoint names that must be hand-labeled, derived from
    _LR_PAIRS/KP_NAMES rather than duplicated as a separate hardcoded list."""
    names = []
    for a, b in _LR_PAIRS:
        left_idx = a if KP_NAMES[a].endswith("_left") else b
        names.append(KP_NAMES[left_idx])
    return names


def validate_raw_points(raw_points: dict) -> None:
    """Fail loudly (single consolidated error) if the raw point set doesn't
    exactly match what's expected — catches drift between a Blender-side
    hardcoded name list and the current KP_NAMES immediately."""
    expected = set(expected_left_names()) | {GROUND_REF_NAME}
    got = set(raw_points.keys())
    missing = expected - got
    extra = got - expected
    if missing or extra:
        problems = []
        if missing:
            problems.append(f"missing: {sorted(missing)}")
        if extra:
            problems.append(f"unexpected: {sorted(extra)}")
        raise ValueError(
            "raw keypoint set does not match expected 12 *_left names + "
            f"'{GROUND_REF_NAME}' — {'; '.join(problems)}"
        )


def detect_axes(raw_points: dict) -> dict:
    """Determine which raw axis (0/1/2) is lateral/longitudinal/height, and
    the sign flips needed to match this project's (x=+left, h=0 ground,
    z=-front/+rear) convention. Raises ValueError with a descriptive message
    on any hard-abort condition. Returns a dict with the resolved mapping
    plus a diagnostics/warnings trail for the health-check report.
    """
    validate_raw_points(raw_points)
    warnings: list[str] = []
    pts = {name: np.asarray(xyz, dtype=np.float64) for name, xyz in raw_points.items()}
    left_names = expected_left_names()
    all_13 = left_names + [GROUND_REF_NAME]

    # --- height axis ---
    front_glass_top = pts["front_glass_top_left"]
    ground = pts[GROUND_REF_NAME]
    h_scores = front_glass_top - ground  # per-axis score, want large positive on the true height axis
    argmins = [min(all_13, key=lambda n: pts[n][axis]) for axis in range(3)]
    h_axis = int(np.argmax(h_scores))
    h_axis_ok = argmins[h_axis] == GROUND_REF_NAME
    diag = "; ".join(
        f"axis{ax}: score={h_scores[ax]:+.3f} argmin={argmins[ax]}" for ax in range(3)
    )
    if not h_axis_ok or h_axis != 2:
        raise ValueError(
            "height-axis detection failed (expected Blender world Z, index 2, to win — "
            "Blender's world space is always Z-up regardless of the source file's own "
            f"up-axis convention). Raw per-axis diagnostics: {diag}. "
            "This usually means a local-vs-world coordinate bug, an unusual parent "
            "transform, or ground_ref was not placed at the true lowest point."
        )
    warnings.append(f"height axis diagnostics — {diag}")

    # --- longitudinal / lateral axis among the remaining two ---
    remaining = [ax for ax in range(3) if ax != h_axis]
    front_w = pts["front_wheel_center_left"]
    rear_w = pts["rear_wheel_center_left"]
    deltas = {ax: rear_w[ax] - front_w[ax] for ax in remaining}
    lon_candidates = [ax for ax in remaining if _LON_WHEELBASE_BAND_M[0] <= abs(deltas[ax]) <= _LON_WHEELBASE_BAND_M[1]]
    lat_candidates = [ax for ax in remaining if abs(deltas[ax]) < _LAT_TRACK_DELTA_MAX_M]
    delta_diag = ", ".join(f"axis{ax}: delta={deltas[ax]:+.3f}m" for ax in remaining)
    if len(lon_candidates) != 1 or len(lat_candidates) != 1 or lon_candidates[0] == lat_candidates[0]:
        raise ValueError(
            "longitudinal/lateral axis detection failed — expected exactly one of the "
            "remaining two axes to show a front/rear wheel separation in "
            f"{_LON_WHEELBASE_BAND_M} m (the known wheelbase) and the other to show "
            f"<{_LAT_TRACK_DELTA_MAX_M} m (front/rear track barely differs). Raw deltas: "
            f"{delta_diag}. Check that front_wheel_center_left/rear_wheel_center_left "
            "weren't swapped or mislabeled."
        )
    lon_axis, lat_axis = lon_candidates[0], lat_candidates[0]
    warnings.append(f"longitudinal/lateral axis diagnostics — {delta_diag}")

    # --- longitudinal sign + origin (wheelbase midpoint, matching build_car_template) ---
    lon_delta = deltas[lon_axis]
    lon_sign = 1.0 if lon_delta > 0 else -1.0
    z_origin = (front_w[lon_axis] + rear_w[lon_axis]) / 2.0

    # --- lateral sign (self-determined: all 12 real points are on the left by construction) ---
    lat_raw_signs = {name: np.sign(pts[name][lat_axis]) for name in left_names}
    pos_votes = sum(1 for s in lat_raw_signs.values() if s > 0)
    neg_votes = sum(1 for s in lat_raw_signs.values() if s < 0)
    majority_sign = 1.0 if pos_votes >= neg_votes else -1.0
    for name, s in lat_raw_signs.items():
        if s != majority_sign and s != 0:
            val = pts[name][lat_axis]
            if abs(val) > _LAT_DISAGREE_HARD_ABORT_M:
                raise ValueError(
                    f"lateral-sign detection failed — '{name}' disagrees with the "
                    f"majority sign on the lateral axis by {val:+.3f}m (> "
                    f"{_LAT_DISAGREE_HARD_ABORT_M}m), which is too large to be click "
                    "noise near the centerline. Check this point wasn't placed on the "
                    "wrong side of the car."
                )
            warnings.append(
                f"'{name}' lateral sign disagrees with majority near centerline "
                f"({val:+.3f}m) — treated as click noise, using majority sign."
            )
    lat_sign = majority_sign
    warnings.append(f"lateral sign: {pos_votes}/{len(left_names)} positive, {neg_votes}/{len(left_names)} negative — using {lat_sign:+.0f}")

    # --- ground-plane origin (+ non-authoritative fallback cross-check) ---
    h_origin = ground[h_axis]
    kp_heights = [pts[name][h_axis] - h_origin for name in left_names]
    min_name = min(left_names, key=lambda n: pts[n][h_axis])
    fallback_gap = min(kp_heights)
    if not (_GROUND_FALLBACK_BAND_M[0] <= fallback_gap <= _GROUND_FALLBACK_BAND_M[1]):
        warnings.append(
            f"ground-plane cross-check WARNING: lowest labeled keypoint ('{min_name}') "
            f"sits {fallback_gap:.3f}m above ground_ref, expected roughly "
            f"{_GROUND_FALLBACK_BAND_M} m (a wheel radius) — double-check ground_ref's "
            "placement."
        )
    else:
        warnings.append(f"ground-plane cross-check OK: lowest keypoint ('{min_name}') is {fallback_gap:.3f}m above ground_ref")

    return {
        "h_axis": h_axis,
        "lon_axis": lon_axis,
        "lat_axis": lat_axis,
        "lon_sign": lon_sign,
        "lat_sign": lat_sign,
        "z_origin": z_origin,
        "h_origin": h_origin,
        "warnings": warnings,
    }


def _raw_to_xhz(raw_xyz, axes: dict) -> tuple[float, float, float]:
    x = axes["lat_sign"] * raw_xyz[axes["lat_axis"]]
    h = raw_xyz[axes["h_axis"]] - axes["h_origin"]
    z = axes["lon_sign"] * (raw_xyz[axes["lon_axis"]] - axes["z_origin"])
    return (x, h, z)


def build_template(raw_points: dict, axes: dict) -> np.ndarray:
    """Apply the axis mapping to the 12 labeled points and mirror to
    produce the full (24, 3) template, in KP_NAMES row order."""
    template = np.zeros((24, 3), dtype=np.float64)
    for a, b in _LR_PAIRS:
        left_idx, right_idx = (a, b) if KP_NAMES[a].endswith("_left") else (b, a)
        name = KP_NAMES[left_idx]
        xhz = _raw_to_xhz(np.asarray(raw_points[name], dtype=np.float64), axes)
        template[left_idx] = xhz
        template[right_idx] = (-xhz[0], xhz[1], xhz[2])
    return template


def compute_dimensions(template: np.ndarray) -> dict:
    """Wheelbase/track/length/height computed from a (24, 3) template.

    height = max(h) directly (not max-min): h=0 already represents true
    ground (via the ground_ref calibration in detect_axes), and wheel
    keypoints now carry real non-zero hub height, so using the range would
    systematically understate true vehicle height by roughly the wheel
    radius. length uses the range since z=0 is the wheelbase midpoint (an
    internal reference), not a body extremity.
    """
    idx = {name: i for i, name in enumerate(KP_NAMES)}

    def dist(name_a, name_b):
        return float(np.linalg.norm(template[idx[name_a]] - template[idx[name_b]]))

    wheelbase = dist("front_wheel_center_left", "rear_wheel_center_left")
    track_width = dist("front_wheel_center_left", "front_wheel_center_right")
    length = float(template[:, 2].max() - template[:, 2].min())
    height = float(template[:, 1].max())
    return {"wheelbase_m": wheelbase, "track_width_m": track_width, "length_m": length, "height_m": height}


def check_dimensions(computed: dict, reference: dict, tolerances: dict) -> list[dict]:
    """Compare computed dims against reference values within tolerances
    (fractions, e.g. 0.15 = ±15%). Returns one check dict per dimension."""
    checks = []
    for key in ("wheelbase_m", "track_width_m", "length_m", "height_m"):
        computed_v = computed[key]
        ref_v = reference[key]
        tol = tolerances[key]
        pct_diff = (computed_v - ref_v) / ref_v * 100.0
        status = "PASS" if abs(pct_diff) <= tol * 100.0 else "WARN"
        checks.append({
            "name": key, "computed": computed_v, "reference": ref_v,
            "pct_diff": pct_diff, "tolerance_pct": tol * 100.0, "status": status,
        })
    return checks


def self_test() -> None:
    """Synthetic round-trip test — no Blender/CAD data needed. Fabricates a
    non-trivial raw-Blender-frame input from a known-good template (reusing
    build_car_template() for the ground truth) and asserts detect_axes +
    build_template recover it exactly."""
    from trafficlab.motion.keypoints_openpifpaf import _FALLBACK_DIMS

    known = build_car_template(dict(_FALLBACK_DIMS))
    idx = {name: i for i, name in enumerate(KP_NAMES)}
    # Give wheels real (non-zero) hub height, matching this tool's intended
    # use — build_car_template's own wheels are h=0, which would degenerately
    # tie with ground_ref's target h=0 below.
    for name in ("front_wheel_center_left", "rear_wheel_center_left",
                 "front_wheel_center_right", "rear_wheel_center_right"):
        known[idx[name]][1] += 0.30

    left_names = expected_left_names()
    known_left = {name: known[idx[name]].copy() for name in left_names}
    front_xhz = known_left["front_wheel_center_left"]
    ground_xhz = np.array([front_xhz[0], 0.0, front_xhz[2]])

    # Fabricate raw Blender-frame data: lon_sign=-1, arbitrary nonzero
    # origin offsets, lateral axis flipped (raw = -x) to exercise sign
    # recovery instead of trivially passing on an identity mapping.
    lon_sign_used = -1.0
    z_origin_offset = 100.0
    h_origin_offset = -53.7

    def forward(xhz):
        # Inverse of _raw_to_xhz: raw_lon = z_origin + lon_sign * z_target
        # (so that lon_sign * (raw_lon - z_origin) == z_target on recovery).
        x, h, z = xhz
        raw = np.zeros(3)
        raw[0] = -x                                    # lateral axis (flipped sign)
        raw[1] = z_origin_offset + lon_sign_used * z    # longitudinal axis
        raw[2] = h + h_origin_offset                    # height axis
        return raw

    raw_points = {name: forward(xhz) for name, xhz in known_left.items()}
    raw_points[GROUND_REF_NAME] = forward(ground_xhz)

    axes = detect_axes(raw_points)
    assert axes["h_axis"] == 2, axes
    assert axes["lon_axis"] == 1, axes
    assert axes["lat_axis"] == 0, axes
    assert axes["lon_sign"] == lon_sign_used, axes
    assert axes["lat_sign"] == -1.0, axes
    assert abs(axes["z_origin"] - z_origin_offset) < 1e-9, axes
    assert abs(axes["h_origin"] - h_origin_offset) < 1e-9, axes

    recovered = build_template(raw_points, axes)
    max_err = float(np.abs(recovered - known).max())
    assert max_err < 1e-9, f"recovered template diverges from known by {max_err}"

    dims = compute_dimensions(recovered)
    dims_known = compute_dimensions(known)
    for key in dims:
        assert abs(dims[key] - dims_known[key]) < 1e-9, (key, dims, dims_known)

    print("SELF-TEST PASSED")
    print(f"  recovered axes: {axes}")
    print(f"  recovered dims: {dims}")
